=== ibcit/BillGenerator/headers/attrib/header-file.dtd
<!ELEMENT airbillPrintout ( Name, Company, Address, City, State, Zip, Country, Phone, Qty, Weight, Reference, SecondRef, Destination, Description, Awb ) >

<!ELEMENT Name ( option+ ) >

<!ELEMENT Company ( option+ ) >

<!ELEMENT Address ( option+ ) >

<!ELEMENT City ( option+ ) >

<!ELEMENT State ( option+ ) >

<!ELEMENT Zip ( option+ ) >

<!ELEMENT Country ( option+ ) >

<!ELEMENT Phone ( option+ ) >

<!ELEMENT Qty ( option+ ) >

<!ELEMENT Weight ( option+ ) >

<!ELEMENT Description ( option+ ) >

<!ELEMENT Destination ( option+ ) >

<!ELEMENT Reference ( option+ ) >

<!ELEMENT SecondRef ( option+ ) >

<!ELEMENT Awb ( option+ ) >

<!ELEMENT option ( #PCDATA ) >

=== ibcit/BillGenerator/headers/awbs/fant.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE header-file SYSTEM "/data/development/codebase/IBCBillGenerator/dist/headers/attrib/header-file.dtd">
<airbillPrintout>
     <Name>
          <option>consignee_name</option>
     </Name>
     <Company />
     <Address>
          <option>consignee_address</option>
     </Address>
     <City>
          <option>consignee_city</option>
     </City>
     <State />
     <Zip>
          <option>consignee_zip</option>
     </Zip>
     <Country>
          <option>consignee_country</option>
     </Country>
     <Phone>
          <option>consignee_tel</option>
     </Phone>
     <Qty>
          <option>Pieces</option>
     </Qty>
     <Outlying />
     <Weight>
          <option>total_weight</option>
     </Weight>
     <Route />
     <Reference>
          <option>customer_ref</option>
     </Reference>
     <SecondRef>
          <option>ref2</option>
     </SecondRef>
     <Destination />
     <Value>
          <option>declare_value</option>
     </Value>
     <CustEmail />
     <CustTaxID />
     <Description>
          <option>product_details</option>
     </Description>
     <Awb>
          <option>tracking_number</option>
     </Awb>
</airbillPrintout>

=== ibcit/BillGenerator/headers/awbs/header2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE header-file SYSTEM "..\attrib\header-file.dtd">
<airbillPrintout>
     <Name>
          <option>NAME</option>
     </Name>
     <Company />
     <Address>
          <option>ADD1</option>
          <option>ADD2</option>
          <option>ADD3</option>
          <option>ADD4</option>
     </Address>
     <City>
          <option>CITY</option>
     </City>
     <State>
          <option>STATE</option>
     </State>
     <Zip>
          <option>ZIP</option>
     </Zip>
     <Country>
          <option>country</option>
     </Country>
     <Phone />
     <Qty>
          <option>pieces</option>
     </Qty>
     <Weight />
     <Reference />
     <SecondRef>
          <option>sec_ref</option>
     </SecondRef>
     <Destination />
     <Description />
     <Awb />
</airbillPrintout>

=== ibcit/BillGenerator/headers/awbs/SOTHEBYS MAINRUN.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE header-file SYSTEM "..\attrib\header-file.dtd">
<airbillPrintout>
     <Name>
          <option>person</option>
     </Name>
     <Company>
          <option>company</option>
     </Company>
     <Address>
          <option>street_1</option>
          <option>street_2</option>
          <option>street_3</option>
     </Address>
     <City>
          <option>city</option>
     </City>
     <State>
          <option>state</option>
     </State>
     <Zip>
          <option>postal</option>
     </Zip>
     <Country>
          <option>country_name</option>
     </Country>
     <Phone>
          <option>telephone</option>
     </Phone>
     <Qty />
     <Weight />
     <Reference>
          <option>cust_num</option>
     </Reference>
     <SecondRef />
     <Destination />
     <Description>
          <option>material_summary</option>
     </Description>
     <Awb />
</airbillPrintout>

=== ibcit/BillGenerator/headers/awbs/header3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE header-file SYSTEM "..\attrib\header-file.dtd">
<airbillPrintout>
     <Name>
          <option>TM Name</option>
     </Name>
     <Company>
          <option>Company</option>
     </Company>
     <Address>
          <option>ADDRESS1</option>
          <option>ADDRESS2</option>
     </Address>
     <City>
          <option>city</option>
     </City>
     <State>
          <option>st</option>
     </State>
     <Zip>
          <option>ZIP</option>
     </Zip>
     <Country>
          <option>Country</option>
     </Country>
     <Phone />
     <Qty>
          <option>TOTAL PCS PER TM</option>
     </Qty>
     <Weight />
     <Reference />
     <SecondRef />
     <Destination />
     <Description />
     <Awb />
</airbillPrintout>

=== ibcit/BillGenerator/headers/awbs/header1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE header-file SYSTEM "..\attrib\header-file.dtd">
<airbillPrintout>
     <Name>
          <option>ATT</option>
          <option>ATT2</option>
     </Name>
     <Company>
          <option>COMPANY</option>
     </Company>
     <Address>
          <option>ADD1</option>
     </Address>
     <City>
          <option>CITY</option>
     </City>
     <State>
          <option>STATE</option>
     </State>
     <Zip>
          <option>ZIP</option>
     </Zip>
     <Country>
          <option>COUNTRY</option>
     </Country>
     <Phone>
          <option>Phone</option>
     </Phone>
     <Qty />
     <Weight />
     <Reference />
     <SecondRef />
     <Destination />
     <Description />
     <Awb />
</airbillPrintout>
