=== ibcit/BillGenerator/profiles/dtd/IBCCustomer.dtd
<!ELEMENT IBCCustomer ( name, account, ref, ref2, company, address, city, state, zip, country, phone ) >
<!ELEMENT account ( #PCDATA ) >
<!ELEMENT address ( #PCDATA ) >
<!ELEMENT city ( #PCDATA ) >
<!ELEMENT company ( #PCDATA ) >
<!ELEMENT country ( #PCDATA ) >
<!ELEMENT name ( #PCDATA ) >
<!ELEMENT phone ( #PCDATA ) >
<!ELEMENT ref ( #PCDATA ) >
<!ELEMENT ref2 ( #PCDATA ) >
<!ELEMENT state ( #PCDATA ) >
<!ELEMENT zip ( #PCDATA ) >

=== ibcit/BillGenerator/profiles/RIO-BANCO BBM - 222.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE IBCCustomer SYSTEM "dtd/IBCCustomer.dtd">
<IBCCustomer>
     <name>BANCO BBM S/A</name>
     <account>222</account>
     <ref />
     <ref2 />
     <company>BANCO BBM S/A</company>
     <address>PRACA PIO X 98 11 ANDAR, CENTRO</address>
     <address2 />
     <city>RIO DE JANEIRO</city>
     <state>RJ</state>
     <zip>20000000</zip>
     <country>BRAZIL</country>
     <phone />
</IBCCustomer>

=== ibcit/BillGenerator/profiles/sourceOne.xml
<?xml version="1.0" standalone="yes"?>
<!DOCTYPE IBCCustomer SYSTEM "dtd/IBCCustomer.dtd">
<IBCCustomer>
	<name>Source One Direct</name>
	<account>6958</account>
	<ref></ref>
	<ref2></ref2>
	<company>Source One Direct, Inc. (D)</company>
	<address>1800-B Northeast Expressway</address>
     <address2 />
	<city>Atlanta</city>
	<state>GA</state>
	<zip>30329</zip>
	<country>US</country>
	<phone>678-420-5021</phone>
</IBCCustomer>

=== ibcit/BillGenerator/profiles/LHR RRDonnelley 55 Bishopsgate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE IBCCustomer SYSTEM "dtd/IBCCustomer.dtd">
<IBCCustomer>
     <name>RR Donnelley Financial</name>
     <account>8147</account>
     <ref>89481</ref>
     <ref2 />
     <company />
     <address>55 Bishopsgate</address>
     <address2 />
     <city>London</city>
     <state />
     <zip>EC2N 3AS</zip>
     <country>England</country>
     <phone>+44 (0)20 7330 1500</phone>
</IBCCustomer>

=== ibcit/BillGenerator/profiles/albertoTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE IBCCustomer SYSTEM "dtd/IBCCustomer.dtd">
<IBCCustomer>
     <name>Alberto Ochoa</name>
     <account>8040</account>
     <ref>5649856</ref>
     <ref2 />
     <company>IBC Miami</company>
     <address>8401 NW 17th St</address>
     <address2 />
     <city>Miami</city>
     <state>Fl</state>
     <zip>33126</zip>
     <country>US</country>
     <phone>305-597-5327</phone>
</IBCCustomer>

=== ibcit/BillGenerator/profiles/emily.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE IBCCustomer SYSTEM "dtd/IBCCustomer.dtd">
<IBCCustomer>
     <name>EMILY USA</name>
     <account>9524</account>
     <ref />
     <ref2 />
     <company>EMILY USA</company>
     <address>11850 WATERSTONE LOOP DR.</address>
     <address2 />
     <city>WINDEREMERE</city>
     <state>FL</state>
     <zip>34786</zip>
     <country>US</country>
     <phone>1-843-592-6689</phone>
</IBCCustomer>

=== ibcit/BillGenerator/profiles/fantassium.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE IBCCustomer SYSTEM "dtd/IBCCustomer.dtd">
<IBCCustomer>
     <name>THE FANTASIUM PROJECTS CORP</name>
     <account>9611</account>
     <ref />
     <ref2 />
     <company>THE FANTASIUM PROJECTS CORP</company>
     <address>1133 BROADWAY</address>
     <address2>.SUITE 641</address2>
     <city>NEW YORK</city>
     <state>NY</state>
     <zip>10010</zip>
     <country>US</country>
     <phone>1-646-638-0433</phone>
</IBCCustomer>
